### ISSUE TITLE
Does not work on Django 1.7

### ISSUE THREAD

**Issue by mikek** [aldryn/aldryn-sites#6]
A few tests fail because of differences in ORM behaviour in Django 1.7 and ALLOWED_HOSTS being unset. Needs further investigation.
```
======================================================================
ERROR: test_auto_configure_site_domain (aldryn_sites.tests.AldrynSitesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./aldryn_sites/tests.py", line 150, in test_auto_configure_site_domain
    Site.objects.all().delete()
  File "[...]/projects/aldryn/aldryn-sites/.tox/py27-dj17/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "[...]/projects/aldryn/aldryn-sites/.tox/py27-dj17/lib/python2.7/site-packages/django/db/models/query.py", line 361, in get
    num if num <= MAX_GET_RESULTS else 'more than %s' % MAX_GET_RESULTS
MultipleObjectsReturned: get() returned more than one Site -- it returned 2!

======================================================================
ERROR: test_auto_configure_site_domain_and_name_if_same (aldryn_sites.tests.AldrynSitesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./aldryn_sites/tests.py", line 162, in test_auto_configure_site_domain_and_name_if_same
    s = Site.objects.get()
  File "[...]/projects/aldryn/aldryn-sites/.tox/py27-dj17/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "[...]/projects/aldryn/aldryn-sites/.tox/py27-dj17/lib/python2.7/site-packages/django/db/models/query.py", line 361, in get
    num if num <= MAX_GET_RESULTS else 'more than %s' % MAX_GET_RESULTS
MultipleObjectsReturned: get() returned more than one Site -- it returned 2!

======================================================================
FAIL: test_auto_configure_allowed_hosts (aldryn_sites.tests.AldrynSitesTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./aldryn_sites/tests.py", line 144, in test_auto_configure_allowed_hosts
    self.assertTrue(domain in settings.ALLOWED_HOSTS, '{} not in ALLOWED_HOSTS'.format(domain))
AssertionError: www.example.com not in ALLOWED_HOSTS

----------------------------------------------------------------------
```

**Comment by mikek** [comment]
Fixed in https://github.com/aldryn/aldryn-sites/commit/4fde03e82c0c35545f3d0f2f0073a3aab9b72d51
